name: teleconsole
version: '0.4.0'
summary: Share your terminal and forward local TCP ports to people you trust.
description: |
  Teleconsole is a free service to share your terminal session with people you
  trust. Your friends can join via a command line using SSH or by using their
  browser. Use it when two parties are separated by NAT and you cannot connect
  via SSH directly.

grade: stable
confinement: classic

apps:
  teleconsole:
    command: teleconsole

parts:
  teleconsole:
    plugin: dump
    source: 
      - on armhf: https://github.com/gravitational/teleconsole/releases/download/0.4.0/teleconsole-v0.4.0-linux-arm.tar.gz 
      - on amd64: https://github.com/gravitational/teleconsole/releases/download/0.4.0/teleconsole-v0.4.0-linux-amd64.tar.gz
      - on i386: fail
      - on arm64: fail
